import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    backgroundColor: "#fff",
    flex: 1,
    justifyContent: "center",
  },
  titleWelcomme: {
    color: "#020202",
    fontFamily: "Avenir",
    fontSize: 20,
    fontStyle: "normal",
    fontWeight: "800",
    lineHeight: 27,
  },
  titleSection: {
    color: "#9B9898",
    fontFamily: "Avenir",
    fontSize: 14,
    fontStyle: "normal",
    fontWeight: "800",
    lineHeight: 19,
  },
  blueBox: {
    backgroundColor: "#334FFA",
    borderRadius: 20,
    height: 143,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 21,
    shadowOffset: { height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    width: 286,
  },
  monthBlueBox: {
    color: "#FFF",
    fontFamily: "Avenir",
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: "800",
    lineHeight: 22,
  },
  totalBlueBox: {
    color: "#FFF",
    fontFamily: "Avenir",
    fontSize: 32,
    fontStyle: "normal",
    fontWeight: "800",
    lineHeight: 44,
    marginTop: 7,
    textAlign: "center",
    justifyContent: "center",
    width: "100%",
  },
  totalContainerBox: {
    width: "100%",
    justifyContent: "center",
    alignItems: "flex-start",
  },
  table: {
    backgroundColor: "#fff",
    borderRadius: 10,
    maxHeight: 350,
    paddingBottom: 20,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 20,
    width: "100%",
  },
  rowTable: {
    width: "100%",
    flexDirection: "row",
    marginBottom: 8,
    justifyContent: "space-between",
  },
  dateText: {
    color: "#000",
    fontFamily: "Avenir",
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 16,
  },
  points: {
    justifyContent: "center",
  },
  containerImg: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingBottom: 32,
    shadowOffset: { height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    width: "100%",
  },
  containerProductInfo: {
    flex: 1,
    justifyContent: "center",
    width: "100%",
  },
  button: {
    alignItems: "center",
    backgroundColor: "#334FFA",
    borderRadius: 10,
    marginTop: 32,
    paddingVertical: 14,
    width: "100%",
  },
  containerRowData: {
    alignItems: "center",
    flexDirection: "row",
    width: "100%",
    maxWidth: 60,
    justifyContent: "flex-end",
  },
});
